name = "dostime-cron"
main = "src/index.js"
compatibility_date = "2026-09-01"

send_email = [{ name = "SEND_EMAIL" }]

[triggers]
crons = ["*/5 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "dostime-db"
database_id = "8ede6c54-b380-4f39-a920-5e284cb7b522"
